[package]
name = "natstest"
version = "0.0.1"
authors = ["Daniel Beecham <daniel@lunix.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nats = "0.9.17"
