#!/usr/bin/python

from xml.dom import minidom;
import _mysql;
import urllib;
import time;
import os;

os.environ['LANG'] = 'en_US.UTF-8'

if __name__ == "__main__":

	# Get armory
	# http://eu.wowarmory.com/guild-info.xml?r=Frostmane&gn=Entropy&rhtml=n
	#	data:
	#		character rank
	# Drag out members
	# foreach member
	#   http://eu.wowarmory.com/character-sheet.xml?r=Frostmane&n=Varya&rhtml=n
	#		data:
	#			character classId genderId level name raceId prefix suffix
	#			talentSpec prim, treeOne, treeTwo, treeThree
	#			skill name, value
	#			health effective
	#			secondBar effective
	#			strength effective
	#			agility effective
	#			stamina effective
	#			intellect effective
	#			spirit effective
	#			armor effective
	#			melee -> power effective
	#			melee -> hitRating value increasedHitPercent
	#			ranged -> powereffective
	#			ranged -> hitRating value increasedHitPercent
	#			hasteRating hastePercent
	#			defense value
	#			dodge percent
	#			parry percente
	#			block percent
	#			resilience value
	#			summary -> c points
	#			
	#   get data from armory
	#   insert into armory (name, data) values ("Varya", "123") on duplicate key update data = "123";
	#   sleep 2
	# delete data more then 30 minutes old
	# 

	db = _mysql.connect("localhost", "root", "pass");

	#xml = minidom.parse("guild.xml");
	#characterXml = minidom.parse("p1.xml");
	xml = minidom.parse(urllib.urlopen("http://eu.wowarmory.com/guild-info.xml?r=Frostmane&gn=Entropy&rhtml=n"));

	strtime = time.strftime("%Y-%m-%d-%H-%M", time.localtime());
	file = open("/home/zhaozhou/src/py/getArmory/logs/" + strtime + "-guild.xml", "w");
	file.write(xml.toxml().encode("utf8"));

	for i in xml.getElementsByTagName("character"):
		time.sleep(3);
		characterXml = minidom.parse(urllib.urlopen("http://eu.wowarmory.com/character-sheet.xml?" + i.getAttribute("url") + "&rhtml=n"));
		file = open("/home/zhaozhou/src/py/getArmory/logs/" + strtime + "-" + i.getAttribute("name") + ".xml", "w");
		file.write(characterXml.toxml().encode("utf8"));

		try:
			name = characterXml.getElementsByTagName("character")[0].getAttribute("name");
			classId = characterXml.getElementsByTagName("character")[0].getAttribute("classId");
			genderId = characterXml.getElementsByTagName("character")[0].getAttribute("genderId");
			level = characterXml.getElementsByTagName("character")[0].getAttribute("level");
			raceId = characterXml.getElementsByTagName("character")[0].getAttribute("raceId");
			prefix = characterXml.getElementsByTagName("character")[0].getAttribute("prefix");
			suffix = characterXml.getElementsByTagName("character")[0].getAttribute("suffix");

			achievements_general = characterXml.getElementsByTagName("c")[0].getAttribute("points");

			rank = i.getAttribute("rank");

			talents = characterXml.getElementsByTagName("talentSpec");
			talentSpecOne = talents[0].getAttribute("prim");
			talentSpecOneTalents = talents[0].getAttribute("treeOne") + "/" + talents[0].getAttribute("treeTwo") + "/" + talents[0].getAttribute("treeThree");

			talentOneIcon = talents[0].getAttribute("icon");

			if len(talents) == 2:
				talentSpecTwo = talents[1].getAttribute("prim");
				talentTwoIcon = talents[1].getAttribute("icon");
				talentSpecTwoTalents = talents[1].getAttribute("treeOne") + "/" + talents[1].getAttribute("treeTwo") + "/" + talents[1].getAttribute("treeThree");
			else:
				talentTwoIcon = ""
				talentSpecTwo = "None"
				talentSpecTwoTalents = ""

			try:
				skillOne = characterXml.getElementsByTagName("skill")[0].getAttribute("name");
				skillOneValue = characterXml.getElementsByTagName("skill")[0].getAttribute("value");
			except:
				skillOne = "None"
				skillOneValue = "0"
			try:
				skillTwo = characterXml.getElementsByTagName("skill")[1].getAttribute("name");
				skillTwoValue = characterXml.getElementsByTagName("skill")[1].getAttribute("value");
			except:
				skillTwo = "None"
				skillTwoValue = "0"

			#db.query("delete from entropy.armory where name = '%s';" % name.encode("utf8"));
			#result = db.store_result();

			db.query("select id from entropy.armory where name = '%s'" % name.encode("utf8"));
			result = db.store_result();

			if db.affected_rows() == 0:
				query = """insert into entropy.armory (name, 
profession_one, 
profession_one_skill, 
profession_two, 
profession_two_skill, 
talent_one, 
talent_one_talents, 
talent_two, 
talent_two_talents, 
classId, 
genderId, 
level, 
raceId, 
prefix, 
suffix,
talent_one_icon,
talent_two_icon,
rank,
achievements_summary,
date) values 
('%s', '%s', '%s', '%s', '%s', 
'%s', '%s', '%s', '%s', '%s', 
'%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', now());""" % (name.encode("utf8"), 
skillOne.encode("utf8"), 
skillOneValue.encode("utf8"), 
skillTwo.encode("utf8"), 
skillTwoValue.encode("utf8"), 
talentSpecOne.encode("utf8"), 
talentSpecOneTalents.encode("utf8"), 
talentSpecTwo.encode("utf8"), 
talentSpecTwoTalents.encode("utf8"), 
classId.encode("utf8"), 
genderId.encode("utf8"), 
level.encode("utf8"), 
raceId.encode("utf8"), 
prefix.encode("utf8"), 
suffix.encode("utf8"),
talentOneIcon.encode("utf8"),
talentTwoIcon.encode("utf8"),
rank.encode("utf8"),
achievements_general.encode("utf8"))

				file.write(query);
				db.query(query);
				result = db.store_result();
			else:
				query = """update entropy.armory set profession_one = '%s', 
profession_one_skill = '%s',
profession_two = '%s',
profession_two_skill = '%s',
talent_one = '%s',
talent_one_talents = '%s',
talent_two = '%s',
talent_two_talents = '%s',
classId = '%s',
genderId = '%s',
level = '%s',
raceId = '%s',
prefix = '%s',
suffix = '%s',
talent_one_icon = '%s',
talent_two_icon = '%s',
rank = '%s',
date = now(),
achievements_summary = '%s' where name = '%s'""" % (skillOne.encode("utf8"), 
skillOneValue.encode("utf8"), 
skillTwo.encode("utf8"), 
skillTwoValue.encode("utf8"), 
talentSpecOne.encode("utf8"), 
talentSpecOneTalents.encode("utf8"), 
talentSpecTwo.encode("utf8"), 
talentSpecTwoTalents.encode("utf8"), 
classId.encode("utf8"), 
genderId.encode("utf8"), 
level.encode("utf8"), 
raceId.encode("utf8"), 
prefix.encode("utf8"), 
suffix.encode("utf8"),
talentOneIcon.encode("utf8"),
talentTwoIcon.encode("utf8"), rank.encode("utf8"), achievements_general.encode("utf8"), name.encode("utf8"))
				file.write(query);
				db.query(query);
				result = db.store_result();
		except:
			pass

	db.query("delete from entropy.armory where date < date_sub(now(), interval 30 minute)");
	result = db.store_result();

	#playerxml = minidom.parse("p1.xml");
	#print playerxml.toxml();
